name: laser_engraving_client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  image: ^3.2.0
  rive: ^0.9.1
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  flutter_riverpod: ^1.0.4
  dough: ^1.0.3


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icons/foreground-windows.png
    - assets/rive/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/launcher_icons/background.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher_icons/foreground.png"
  image_path: "assets/launcher_icons/foreground.png"
  web:
    generate: true
    image_path: "assets/launcher_icons/foreground.png"
    background_color: "#000000"
    theme_color: "#F37410"
  windows:
    generate: true
    image_path: "assets/launcher_icons/foreground-windows.png"
    icon_size: 255 # min:48, max:256, default: 48